
spring:
  jpa:
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: none
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
  datasource:
    url: ${DB_URL:jdbc:hsqldb:mem:mydb}
    username: ${DB_USER:SA}
    password: ${DB_PASSWORD:}
    driverClassName: ${DB_DRIVER:org.hsqldb.jdbc.JDBCDriver}
    tomcat:
      max-wait: 10000
      max-active: 10000
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.footballinventory: DEBUG
    org.hibernate: INFO